services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.3}
    environment:
      COMPOSER_CACHE_DIR: /tmp/composer-cache
    volumes:
      - .:/app
      - composer-cache:/tmp/composer-cache
    working_dir: /app

volumes:
  composer-cache:
